### ISSUE TITLE
Mechs stand outside base dont attack walls.

### ISSUE THREAD

**Issue by pogoman** [kbatbouta/CAI-5000#63]
Hey mate, love the mod. Was running an old fork from December until now. To deal with the AI in this mod i generally wall my entire base and have individual pawns take snapshots at raiders from various exits (running CE as well). I noticed the new release (lts-stable-a1) and thought i would compare how a particular mech raid that's been troubling me behaved on the new version, however on this new version the mechs dont even try to breach the walls and just afk outside my base until i open a door. If i close the door they go back to afking. Im playing on the hard setting.

Again thanks for the mod cant play rimworld without it :)

**Comment by pogoman** [comment]
Ok more info here now. spawned some normal raids with dev mode and they breach the walls as per usual. Its just the mech raids that afk outside.

**Comment by kbatbouta** [comment]
Fixed in the latest update.

**Comment by pogoman** [comment]
Can we open please. This issue still exists with fast reactions enabled for normal mech raids like militors. Even with fast reactions off eventually if enough of them die outside a door they stop trying to come in at all. They dont try to dig anywhere.

**Comment by pogoman** [comment]
For more context see the pic below: 
![cai](https://user-images.githubusercontent.com/2501110/222421555-cff43063-170a-452c-9bcf-cd598ae43be1.png)
In the picture that door is essentially the only entrance to my base. Every other external aspect of it is just walls. Now obviously a lot of militors have died trying to break down the door and "Grunt" been shooting them through the embrasure. Now i like that the AI has decided to no longer try to breach this door because it is clearly suicide. However now instead of trying to breach elsewhere, the militors just afk in the wandering state. And to be clear if i am standing there with fast reactions enabled its even worse; when the raid starts they do not even try to breach the door at all. Again its great they recognise it as a killbox of sorts, but why arent they trying to dig elsewhere?
